### ISSUE TITLE
units in seconds instead of h:m:s

### ISSUE THREAD

**Issue by BartmanEH** [EricBerendsen/dvbinspector#12]
Thank you for your useful DVB inspector program. I managed to get it up and running pretty easily on my Mac due to your hard work making it a stand-alone .jar. Once I fiddled with some permissions for Java on my system, I was able to browse and analyze files in my Downloads folder. For the record, here's what I had to do: give Full Disk Access to JavaLauncher via:
`Settings->Security & Privacy->Full Disk Access` and add `/System/Library/CoreServices/JavaLauncher`

I would like to see values in seconds rather than hh:mm:ss. For example, in a SCTE-35 message, I see:
```
TableType: user defined / SCTE3 - Splice_info_section (SCTE-35) (0/0)
[redacted]
+-table_id: 0xFC (252) => user defined / SCTE3 - Splice_info_section (SCTE-35)
[redacted]
+-splice_insert
[redacted]
| +-splice_time
[redacted]
| | +-pts_time: 0x647FA2E3 (1686086371) => 5:12:14.2930
| +-break_duration
[redacted]
| | +-duration: 0x7BA0CE (8102094) => 0:01:30.0232
```
1) I would like to see pts_time in plain seconds (expected value: 1686086371/90000=18734.293) rather than hh:mm:ss.ssss
2) Is there some text cutoff for table id 0xFC and TableType?
          perhaps `user defined / SCTE3 - Splice_info_section (SCTE-35)`
       should be `user defined / SCTE35 - Splice_info_section (SCTE-35)`

**Comment by EricBerendsen** [comment]
Hi, Thank you for your feedback. I was not aware it takes so much effort to run a java application on a Mac. 

1. I think in general the hh:mm:ss format is easier to read. It is also used in other analysers, making it easier to compare results. If changed it would have to be changed all over the program, so not a small change. I am thinking about making it a user preference, switchable from the settings menu.
2. Yes, that is a typo. Will be fixed in next release. Should be "user defined / SCTE - Splice_info_section (SCTE-35)" where the first SCTE indicates the organization that defines the standard. Like "user defined / ATSC - Satellite VCT (SVCT)" for table id 0xDA .

**Comment by BartmanEH** [comment]
1. It is precisely because I am comparing results to the Sencore Compressed Media Analyzer that I suggest raw seconds. Here's a screen shot showing Cmd time and Splice time in simply Seconds:
<img width="1621" alt="scte_info_channel_600_20210119" src="https://user-images.githubusercontent.com/6135879/105422001-04395e00-5c11-11eb-996f-792977a06a97.png">
A user preference would be great but it sounds like it will take some time to implement. In the meantime, I can convert manually.

3. (new) What I really need is the Preroll timing: comparing the PTS of when the splice will execute against the PTS of when the command was issued. This is something only the Compressed Media Analyzer provides--no other analyzer I've tried has this feature. Maybe you can think of some way to implement it?
