### ISSUE TITLE
Copy Item / Sub Tree to Clipboard only copies up to 0x64 bytes for private data, any data after that is missing

### ISSUE THREAD

**Issue by tomyummmm** [EricBerendsen/dvbinspector#64]
Hi as mentioned above, I tried this on DSM-CC PID, and the private data when pasted out is truncated to only the first 0x64 bytes.

**Comment by EricBerendsen** [comment]
"It's not a bug, it's a feature"... In the tree view it does not make sense to show very long strings of hex numbers. Difficult to read, and it makes the horizontal scrollbar very small. So that is why only the first 100 bytes are shown. When the node is selected the whole data can be viewed in the right panel. Also the bytes can be saved to file by right clicking and selecting "Save bytes as...".

The copy item / sub tree just copies the tree view. So it will truncate that as well. 

I have added a warning that not all data is shown, that should prevent any  possible confusion;

![image](https://github.com/EricBerendsen/dvbinspector/assets/50879515/a442fe28-d3d7-43f2-a237-50ed6b1a5326)

**Comment by tomyummmm** [comment]
Hi, I was asking if it was possible to have all bytes copied to clipboard, as this would be easier for me to paste into a text file for quicker analysis. Currently it only copies up to the truncated 0x64. I understand not showing all bytes in tree view of the program for a cleaner look, but it would be nice if all bytes were copied into clipboard.

The "save bytes as" option does not show up when right clicking on the entire tree? I prefer the way all of the data formatted as is shown in tree view.

**Comment by EricBerendsen** [comment]
Hi, the copy to clipboard is just a literal copy of the tree view. Changing that behaviour would be a major effort, so that is not planned for now. 

If you really want to change the truncation that for your local version, it is in KVP.java, in the method appendHexBytes(final StringBuilder b) (line 3630. 

The save bytes as...  only saves one byte[] as binary. So not formatted as hexadecimal.  This way you can open it in a hex-edit or whatever for further processing.
